### PR TITLE
Android  support

### PR DESCRIPTION
**Pull request by artyom-beilis**
I'm starting it since I was looking to be able to use it on Android.  Basic difference that must be handled:

1. You need to be able to open camera given file descriptor that was open for you.
    
    Android permission model does not allow device discovery or opening device directly. I can only receive a file descriptor of an opened device and work with it.
    
    I added it as drop in replacement of search function [when fd is provided](https://github.com/artyom-beilis/libgphoto2_android_support/blob/b86c032afdd32cebdb1f97221d7e3195560383f6/libgphoto2_port/libusb1/libusb1.c#L179)
2. Android requires having all libraries/shared object being on one flat directory. 

    So I changed naming of camera and io libraries, to `libgphoto_port_iolibs_XXX` for example `libgphoto_port_iolibs_libusb1` and `libgphoto_camlibs_ptp2` and [I filter them by pattern during load like this](https://github.com/artyom-beilis/libgphoto2_android_support/blob/b86c032afdd32cebdb1f97221d7e3195560383f6/libgphoto2_port/libgphoto2_port/gphoto2-port-info-list.c#L243)

Finally I unfortunately failed to build the library using autotools - libtool is failing to build shared object for some reason. I tested with some small autotools based projects and they worked but not libgphoto. Currently I created CMake files to build the project... I hope I'll be able to resolve the issue with auto-tools but actually CMake may help me using libgphoto on Windows... so this is something probably temporary.

Now big open question:

I need to pass the file descriptor to libusb1 io library. I first I thought to use GPPortInfo... setting path to something like `usb:fd=NNN`. But I need to specify ALL parameters including path to library. Currently `gp_port_set_library_path` isn't even implemented. From what I have seen so far user can receive a list of "Infos" and select one. In my case I must provide something that library does not know.

I currently implemented [an external function for libusb1](https://github.com/artyom-beilis/libgphoto2_android_support/blob/b86c032afdd32cebdb1f97221d7e3195560383f6/libgphoto2_port/libusb1/libusb1.c#L125). I link directly to it and I set file descriptor than I start libgphoto initialization.

I really don't like this method and I'd like to pass this file descriptor via library interface. What is recommended way of doing it?

Bottom like: this is work in progress but I want to consult with libgphoto developers to make sure my changes will be accepted back at some point

### CODE REVIEW

**Comment by artyom-beilis** [comment]
I managed to make autotools work for Android so I did some changes, also I modified API for sysdevice access:

```
/** 
 * \brief Allow using file descriptor of USB device without auto-discovery
 *
 * This is required for access of USB on android since applications don't have direct
 * access to USB device
 * 
 * It must be called prior to library initialization
 */
int gp_port_usb_set_sys_device(int fd);

/** 
 * \brief Get externally set file descriptor of USB device, return -1 if not set
 */
int gp_port_usb_get_sys_device(void);
```

So you can set fd via `libgphoto2_port` library

**Comment by laheller** [comment]
@artyom-beilis
Nice!

> Finally I unfortunately failed to build the library using autotools - libtool is failing to build shared object for some reason.

Here is how I built libtool for Android:
https://github.com/gphoto/libgphoto2/issues/335#issuecomment-881946081

BR,

Ladislav

**Comment by artyom-beilis** [comment]
> Here is how I built libtool for Android:

Actually I finally managed to do it using autotools. The problem with libtool and actually automake of libgphoto2 was incorrect build command in generated libtool file. I'll get to my dev machine and I'll put it there.

So now I can build everything using standard autotools. I'll remove CMakes from this pull since they aren't complete in general.

**Comment by laheller** [comment]
@msmeissn
This is an old story, maybe now it's the time also for Android...

**Comment by laheller** [comment]
@hfiguiere @ndim @msmeissn 

Hi!

Any chance to make this happen?

BR,

Ladislav

**Comment by msmeissn** [comment]
can you rebase the patch to remove the conflicts?

**Comment by laheller** [comment]
@artyom-beilis

**Comment by artyom-beilis** [comment]
@msmeissn Rebase you mean lineup with latest version?

2nd question where should I write Android specific notes - because it requires some preparation to run on Android

**Comment by artyom-beilis** [comment]
# Here the current status/notes for Android use

Under android you can't discover UBS devices - you don't have permissions. Only you can receive a file descriptor for the UBS device after user gave permission. So it is needed to pass this file descriptor to the gphoto2 as if it is discovery.

Second issue is file layout. Android has very specific naming and does not allow nested directories for libraries. So every camera and port lib should be renamed

`lib/libgphoto2/2.5.31.1/canon.so` to `lib/libgphoto2_camlib_canon.so`
`lib/libgphoto2_port/0.12.2/usb1.so` to `lib/libgphoto2_port_iolib_usb1.so`

Here is the code for renaming where PRFX in installation prefix

   for f in $PRFX/lib/libgphoto2/*/*.so
    do
        mv -v $f $PRFX/lib/libgphoto2_camlib_$(basename $f)
    done
    for f in $PRFX/lib/libgphoto2_port/*/*.so
    do
        mv -v $f $PRFX/lib/libgphoto2_port_iolib_$(basename $f)
    done

To load cameras and port libraries you need to setup environment variables:

        setenv("CAMLIBS",libdir,1);
        setenv("IOLIBS", libdir,1);
        setenv("CAMLIBS_PREFIX","libgphoto2_camlib_",1);
        setenv("IOLIBS_PREFIX","libgphoto2_port_iolib_",1);

Where libdir is actual directory the files are installed in. You can get it via `getApplicationInfo().nativeLibraryDir`. Note make sure to set in manifest `android:extractNativeLibs="true"`

And once you receive file descriptor of USB device configure it before you call the open camera API `gp_port_usb_set_sys_device(fd);` It would simulate "search" and will find only the device with provided file descriptor.

Note you need to have latest libubs1 library that supports `libusb_wrap_sys_device` API

**Comment by msmeissn** [comment]
> How much sense does it still make these days to have all the camlibs and iolibs dynamically loaded? The flat layout thing would be entirely unnecessary if we were to just link all the camlibs into libgphoto2 and all iolibs into libgphoto2_port.
> 
> I have seen two patches doing that, even though I have tested neither yet at this time.

@ndim I think these days we can have just a single library, which would make things easier. people dont seem to provide pluggable drivers or so, they all rebuilds anyway.

**Comment by artyom-beilis** [comment]
I lined it all up to master. 

So far it had been tested by multiple users of [OpenLiveStacker](https://github.com/artyom-beilis/OpenLiveStacker) and seems to be Ok

**Comment by jamie-ward** [comment]
Great work! This is incredible... I'm trying to implement this into my own android project and I'm a bit of a n00b when it comes to this. Are you able to give any advice on how to get this running in my own project? Currently maintaining my own ptp library in kotlin and would be amazed if I could this into my project.

**Comment by artyom-beilis** [comment]
> Great work! This is incredible... I'm trying to implement this into my own android project and I'm a bit of a n00b when it comes to this. Are you able to give any advice on how to get this running in my own project? Currently maintaining my own ptp library in kotlin and would be amazed if I could this into my project.

My project mostly uses C++ tiny Java wrapper. So you need to create some binding code between C or C++ and Java/Kotlin.

**Comment by jamie-ward** [comment]
> > Great work! This is incredible... I'm trying to implement this into my own android project and I'm a bit of a n00b when it comes to this. Are you able to give any advice on how to get this running in my own project? Currently maintaining my own ptp library in kotlin and would be amazed if I could this into my project.
> 
> My project mostly uses C++, and only tiny Java wrapper around C++ project. So you need to create some binding code between C or C++ and Java/Kotlin for libgphoto

That's great! Have a bit of experience binding code for rust and kotlin so I'll give this a try.

Thanks again.

**Comment by artyom-beilis** [comment]
> > > Here is how I built libtool for Android:
> > 
> > 
> > Actually I finally managed to do it using autotools. The problem with libtool and actually automake of libgphoto2 was incorrect build command in generated libtool file. I'll get to my dev machine and I'll put it there.
> > So now I can build everything using standard autotools. I'll remove CMakes from this pull since they aren't complete in general.
> 
> Out of interest, what was the fix? Currently falling into a similar issue with libtool and autoconf not auto detecting it

The generated libtool file has incorrect value of `archive_cmds=""` it should be 

    archive_cmds="\$CC -shared -nostdlib \$predep_objects \$libobjs \$deplibs \$postdep_objects \$compiler_flags -o \$lib

Once it fixed the build succeeds. Below the script that I use to build the library for all 4 architechtures - of course some paths are local but it can be easily adapted.

Of course you also need libltdl library as well (it fails with same error)

[android_bash.txt](https://github.com/gphoto/libgphoto2/files/13479121/android_bash.txt)

**Comment by zoe-zywang** [comment]
> > > > Here is how I built libtool for Android:
> > > 
> > > 
> > > Actually I finally managed to do it using autotools. The problem with libtool and actually automake of libgphoto2 was incorrect build command in generated libtool file. I'll get to my dev machine and I'll put it there.
> > > So now I can build everything using standard autotools. I'll remove CMakes from this pull since they aren't complete in general.
> > 
> > 
> > Out of interest, what was the fix? Currently falling into a similar issue with libtool and autoconf not auto detecting it
> 
> The generated libtool file has incorrect value of `archive_cmds=""` it should be
> 
> ```
> archive_cmds="\$CC -shared -nostdlib \$predep_objects \$libobjs \$deplibs \$postdep_objects \$compiler_flags -o \$lib
> ```
> 
> Once it fixed the build succeeds. Below the script that I use to build the library for all 4 architechtures - of course some paths are local but it can be easily adapted.
> 
> Of course you also need libltdl library as well (it fails with same error)
> 
> [android_bash.txt](https://github.com/gphoto/libgphoto2/files/13479121/android_bash.txt)

What is the meaning of the "AROOT=/home/artik/Packages/Android/$arch"? Android SDK?
If it means SDK, what is the version of it?

**Comment by artyom-beilis** [comment]
> What is the meaning of the "AROOT=/home/artik/Packages/Android/$arch"? Android SDK?
> If it means SDK, what is the version of it?

AROOT is a location of the packages I build for Android (outside SDK) for example libtool, libusb

**Comment by zoe-zywang** [comment]
> > What is the meaning of the "AROOT=/home/artik/Packages/Android/$arch"? Android SDK?
> > If it means SDK, what is the version of it?
> 
> AROOT is a location of the packages I build for Android (outside SDK) for example libtool, libusb

Thanks a lot, I think that it belongs in an output folder. ^^

**Comment by Thammada** [comment]
> > > > Here is how I built libtool for Android:
> > > 
> > > 
> > > Actually I finally managed to do it using autotools. The problem with libtool and actually automake of libgphoto2 was incorrect build command in generated libtool file. I'll get to my dev machine and I'll put it there.
> > > So now I can build everything using standard autotools. I'll remove CMakes from this pull since they aren't complete in general.
> > 
> > 
> > Out of interest, what was the fix? Currently falling into a similar issue with libtool and autoconf not auto detecting it
> 
> The generated libtool file has incorrect value of `archive_cmds=""` it should be
> 
> ```
> archive_cmds="\$CC -shared -nostdlib \$predep_objects \$libobjs \$deplibs \$postdep_objects \$compiler_flags -o \$lib
> ```
> 
> Once it fixed the build succeeds. Below the script that I use to build the library for all 4 architechtures - of course some paths are local but it can be easily adapted.
> 
> Of course you also need libltdl library as well (it fails with same error)
> 
> [android_bash.txt](https://github.com/gphoto/libgphoto2/files/13479121/android_bash.txt)

@artyom-beilis I'm not familiar with C build tools and I need some guidance.
What do you mean by the generated libtool file? Which file am I supposed to set archive_cmds ?
Currently when running your android_bash script, I got this error
```
...
checking for libltdl... autodetecting
checking for libltdl at default location... no
checking for libltdl at /usr/local... no
configure: error:
libgphoto2 requires libltdl (a part of libtool)

Please make sure that the proper development package is installed
(may be called libltdl-dev, libtool-ltdl-devel, libltdl, etc.) and if
the autodetection fails, that the LTDLINCL and LIBLTDL variables are
set properly on the configure command line.
```

However, `libltdl-dev` has already been installed.

When running `./configure` it seems to be OK for these specific instructions.
```
...
checking for libltdl... autodetecting
checking for libltdl at default location... yes
checking LTDLINCL (autodetected)...
checking LIBLTDL (autodetected)... -lltdl
...
```

**Comment by artyom-beilis** [comment]
Note libltdl is should be built for Android as well - it is the dependency. "Normal" configure finds native - host libltdl when cross compiling to Android you need dependency of libltdl as well.

**Comment by NeedNot** [comment]
I can't wrap my head around how to actually build for android arm64-v8a.
1. Before I waste my time figuring it out, will the library be able to be used on a normal android device without root? (App asks for permissions)
2. I get that i need to build each dependency for libgphoto2 for arm64 and build libgphoto2 with them. But how and which ones?

We need a straight forward guide

**Comment by artyom-beilis** [comment]
1. Yes it cam be used in normal app. This is why I ported it and it runs inside Openlivestacker app it is on Google play 2. You need AFAIR two libusb and libtldl I don't recall if libgphoto uses libraw and libjpeg. So you need to build these deps
Read this for more details https://github.com/gphoto/libgphoto2/pull/918#issuecomment-1775150720

Artyom  
 
  On יום ו׳, אוג׳ 29, 2025 at 21:28, ***@***.***> wrote:   NeedNot left a comment (gphoto/libgphoto2#918)
I can't wrap my head around how to actually build for android arm64-v8a.
   
   - Before I waste my time figuring it out, will the library be able to be used on a normal android device without root? (App asks for permissions)
   - I get that i need to build each dependency for libgphoto2 for arm64 and build libgphoto2 with them. But how and which ones?

We need a straight forward guide

**Comment by NeedNot** [comment]
> 1. Yes it cam be used in normal app. This is why I ported it and it runs inside Openlivestacker app it is on Google play 2. You need AFAIR two libusb and libtldl I don't recall if libgphoto uses libraw and libjpeg. So you need to build these deps Read this for more details [#918 (comment)](https://github.com/gphoto/libgphoto2/pull/918#issuecomment-1775150720) Artyom  On יום ו׳, אוג׳ 29, 2025 at 21:28, ***@***.***> wrote: NeedNot left a comment ([gphoto/libgphoto2#918](https://github.com/gphoto/libgphoto2/pull/918)) I can't wrap my head around how to actually build for android arm64-v8a. - Before I waste my time figuring it out, will the library be able to be used on a normal android device without root? (App asks for permissions) - I get that i need to build each dependency for libgphoto2 for arm64 and build libgphoto2 with them. But how and which ones? We need a straight forward guide — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Very very helpful, After days of ripping my hair out I've finally got everything to build and now i'm able to build my android app. Just caught up trying to open the camera.

to quote this part

> And once you receive file descriptor of USB device configure it before you call the open camera API `gp_port_usb_set_sys_device(fd);` It would simulate "search" and will find only the device with provided file descriptor.

my current c++ code looks like this for connecting to the camera
```cpp
  {
    int ret = gp_camera_new(&gp_camera_);
    if (ret < GP_OK)
    {
      running_ = false;
      throw std::runtime_error("Camera initialization failed");
    }
    ret = gp_camera_init(gp_camera_, gp_context_);
    if (ret < GP_OK)
    {
      running_ = false;
      gp_camera_free(gp_camera_);
      throw std::runtime_error("Camera connection failed");
    }
  }
  ```
  
  I am correct before I can execute that code I have to do this
  `gp_port_usb_set_sys_device(fd);`
  
  and before calling any native code do this?
  `val connection = usbManager.openDevice(e.value)` and pass `connection.fileDescriptor`?
  
  If so then I'm doing something wrong because I'm still getting
  `terminating due to uncaught exception of type std::runtime_error: Camera connection failed`

**Comment by artyom-beilis** [comment]
Note there are several steps important steps:

1. Rename port/camera and put them into libs directory and rename them:
     lib/libgphoto2/2.5.31.1/canon.so to lib/libgphoto2_camlib_canon.so
     lib/libgphoto2_port/0.12.2/usb1.so to lib/libgphoto2_port_iolib_usb1.so
2. Make sure to configure android:extractNativeLibs="true" in the manifest, see example: https://github.com/artyom-beilis/android_live_stacker/blob/web_ols/app/src/main/AndroidManifest.xml#L5 otherwise dlopen would not work
3. Setup environment variables (before you load anything) - you need to query where the lib directory from Java API: see 

    https://github.com/artyom-beilis/OpenLiveStacker/blob/main/src/gphoto2_camera.cpp#L823

 4. Make sure you save log file it would help to see errors using gp_log_add_func

Artyom

**Comment by NeedNot** [comment]
It appears everything is loading correctly. It's just not finding the camera.
https://gist.github.com/NeedNot/34e2480c86f5b8bd367bbabd1f47696c

For testing right now when i click start it does this
```kotlin
val connection = usbManager.openDevice(e.value)
println("Connecting to device ${e.value.manufacturerName} ${e.value.productName}")
skiVision.start(connection.fileDescriptor)
```
and i'm doing this gp_port_usb_set_sys_device(fd); before it attempts to connect to the camera. And yet it still crashes.

**Pull request merged**
