### PR TITLE
Fix build on Mac OS X

### LINKED ISSUE #952: 'ushort' not compiling correctly on mac
**Describe the bug**

@colinleroy  recently added quicktake support doesn't compile on Mac due to unknown type 'ushort'

( which is strange? since type headers should convert 'ushort' into apple's 'unsigned short' )

( not blocking, no urgency. but happened to run across )

**libgphoto2 and gphoto2 version**
latest master (08d0369)

**To Reproduce**

Mac OS Ventura 13.5.2 (22G91)

```
$ gcc --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D_GPHOTO2_INTERNAL_CODE -DLOCALEDIR=\"/usr/local/share/locale\" -DCAMLIBS=\"/usr/local/lib/libgphoto2/2.5.31.1\" -I.. -I.. -I../libgphoto2_port -I/opt/homebrew/include -g -O2 -Werror=unknown-warning-option -Wall -Wextra -Wmost -Werror=incompatible-pointer-types -Werror=implicit -Werror=int-conversion -Wno-error=reserved-identifier -Wno-error=documentation-deprecated-sync -Wno-unused-parameter -c quicktake1x0/qtk-helpers.c  -fno-common -DPIC -o quicktake1x0/.libs/la-qtk-helpers.o
quicktake1x0/qtk-helpers.c:74:59: error: unknown type name 'ushort'; did you mean 'short'?
unsigned char getbithuff (int nbits, unsigned char **raw, ushort *huff)
                                                          ^~~~~~
                                                          short
quicktake1x0/qtk-helpers.c:74:15: error: conflicting types for 'getbithuff'
unsigned char getbithuff (int nbits, unsigned char **raw, ushort *huff)
              ^
quicktake1x0/quicktake1x0.h:75:15: note: previous declaration is here
unsigned char getbithuff (int nbits, unsigned char **raw, unsigned short *huff);
              ^
2 errors generated.
```

( https://github.com/gphoto/libgphoto2/blob/08d03695ead88ceeb0cdf1cc83910bfee80220c8/camlibs/quicktake1x0/qtk-helpers.c#L74 )

### PR DESCRIPTION
**Pull request by colinleroy**
Fixes #952

### CODE REVIEW

**Comment by msmeissn** [comment]
thanks, i saw the freebsd failures but was struggling a bit on them

**Comment by colinleroy** [comment]
> thanks, i saw the freebsd failures but was struggling a bit on them

Apparently including unistd.h is not enough... Sorry about that, I don't know why!

**Comment by msmeissn** [comment]
There are some #define _FOO_SOURCE on top of those files, which we thought will help macOS / darwin builds, but they occasionaly block various other standard library functions.

**Comment by hfiguiere** [comment]
`uint16_t` with `#include <stdint.h>` should be the type used

types like `int` and `short` should be left behind.

**Pull request merged**
