### PR TITLE
Canon Object Change Support

### PR DESCRIPTION
**Pull request by littlexiang**
I've test several model and find that for camera file change case like "Rating" or "Protect"
under firmware <=1.1.0 the event is PTP_EC_CANON_EOS_ObjectInfoChangedEx (tested with D1300, ver 1.1.0, purchased recently,  I think it's the most cheap model now)
and above firmware >=1.1.3 the only event is PTP_EC_CANON_EOS_ObjectContentChanged (tested with 1DX Mark II, ver 1.1.3 & 1.1.6 purchased mid 2017)

so this PR is an upgrade to my last PR, 
it's now compatible for both events and returns the same result of object path and filename

### CODE REVIEW

**Comment by msmeissn** [comment]
itwould be cool if you could rebase uyour branch against master and send another pull request. you can also merge the fix double free into the original commit

**Comment by littlexiang** [comment]
@msmeissn thx a lot. could you pls tell me the firmware version of your camera?
I would try to reset my repo master and make a clean PR, maybe squash all the commits into one

**Comment by msmeissn** [comment]
it show 1.0.0 as firmware version.

**Comment by littlexiang** [comment]
FYI my D1300 (v1.1.0) emits both events when single meta info change happens, so this event will be triggered twice

**Pull request merged**
