### PR TITLE
White balance adjust on Canon 1300D

### PR DESCRIPTION
**Pull request by evertheylen**
On my Canon 1300D, I was unable to adjust the white balance to negative values (both `whitebalanceadjusta` and `whitebalanceadjustb`). This is problematic, since it would limit the possible WB settings to a quarter of the possibilities. The horizontal Blue-Amber axis is controlled by `whitebalanceadjusta` (positive values are amber), the vertical Green-Magenta axis is controlled by `whitebalanceadjustb` (positive values are green).
  
White Balance Shift

When trying to set negative values, I got a "Device is busy" error (code -110). Getting the value worked fine (if set on the camera UI).

After some debugging I found out that it did work when I used a 32 bit integer instead of a 16 bit one. I tried to properly rewrite this to the best of my abilities, but I could not get the `_get` function to 'automatically' detect the possible values. I have no idea where they are set and how I could modify this in a clean way, so any feedback is welcome :) . Currently, I just hardcoded it.

Also, I have no idea what implications this may bring for other Canons. More testing might be needed, but I only have a Canon 1300D available.

### CODE REVIEW

**Comment by msmeissn** [comment]
can you attach a debuglogfile for --list-all-config ?

**Comment by evertheylen** [comment]
They won't differ much from the ones in my issue: #198. Those are using the latest release, here is a debug log using my branch, with the setting B8, M4.
[B8-M4-debug.txt](https://github.com/gphoto/libgphoto2/files/1251423/B8-M4-debug.txt)

**Comment by msmeissn** [comment]
hmm. your 1300D sends 32bit entities for those values, while the older ones send 16bit entities. I need to think how to handle this commonly for both

**Comment by msmeissn** [comment]
i will revert the last patch as I fixed that issue, rest is ok

**Pull request merged**
