### PR TITLE
Add Sony Alpha 7 IV (ILCE-7M4) Support

### PR DESCRIPTION
**Pull request by nakato**
This is another case of ptp_sony_9280 causing USB to hang.  Ref #85
Add ILCE-7M4 to the exclude of the ptp_sony_9280 call.

This is followed by two further patches.
One, adding the USB ID for the device, which isn't strictly necessary, but nice to have.
And the other filling in the obvious missing values in CompressionSetting and AspectRatio.

### CODE REVIEW

**Comment by SiuyuenChow** [comment]
@nakato 
hi nakato,
When you use Sony Alpha 7 IV (ILCE-7M4), can you get data normally?
I recently had trouble getting the file path and name.

**Comment by jaredmdobson** [comment]
@SiuyuenChow I can't get file and folders with it.

**Comment by nakato** [comment]
This patch isn't included in a released version of libgphoto2 yet as far as I'm aware.  To use it you'll need to build a development version and ensure the dev library is used over any packaged copy.

I've built and installed a clean copy of this from git just now to check, and I can list folders.  A caveat however is that if access is first attempted with a non-patched copy you have to either send a reset with `--reset` or re-plug the camera, otherwise the camera won't respond to commands.  Some software may attempt to access the camera as soon as it is attached.

I can list folders on my camera, however, the commands are excruciatingly slow, and I have not looked into why.  When I tried to start a transfer to copy the photos off the camera, I saw it was going to take over 24 hours, so I canceled that and I have only transferred 5 photos off the camera with libgphoto2 so far.

For example, this took 2.25min to complete:
```
% time gphoto2 -l
There is 1 folder in folder '/'.                                               
 - store_00010001
There are 67 folders in folder '/store_00010001'.
 - 2022-02-25
...
 - 2022-06-26
There are 0 folders in folder '/store_00010001/2022-02-25'.
There are 0 folders in folder '/store_00010001/2022-02-26'.
...
There are 0 folders in folder '/store_00010001/2022-06-26'.
gphoto2 -l  0.43s user 0.52s system 0% cpu 2:14.70 total
```

I'm not sure what the cause of the slowness is, and I gave up looking into it when I decided I wanted to actually read the PTP standard before really digging into it and found it prohibitively expensive, though I don't think that was directly related to the slowness and more wanting to gain some background on how it works.

**Comment by SiuyuenChow** [comment]
> commands

@nakato 

On SONY, I ran into a problem where I couldn't get the file path and name when listening for photos.

https://github.com/gphoto/libgphoto2/issues/794

sony PTPObjectInfo :
(PTPObjectInfo) oi = {
StorageID = 65536
ObjectFormat = 14337
ProtectionStatus = 0
ObjectCompressedSize = 316688
ThumbFormat = 0
ThumbCompressedSize = 0
ThumbPixWidth = 0
ThumbPixHeight = 0
ImagePixWidth = 0
ImagePixHeight = 0
ImageBitDepth = 0
ParentObject = 0
AssociationType = 0
AssociationDesc = 0
SequenceNumber = 0
Filename = 0x0000000280ca8170 "DSC00152.JPG"
CaptureDate = 0
ModificationDate = 0
Keywords = 0x0000000000000000
}

**Pull request merged**
