### PR TITLE
Remove stdint.h shim

### PR DESCRIPTION
**Pull request by Zeranoe**
stdint.h has wide adoption at this point, so it should be safe to use.

### CODE REVIEW

**Comment by ndim** [comment]
No argument about normal post 2010 Linux systems from me.

Some people are building for weird systems, though.

**Comment by msmeissn** [comment]
i wonder since how long this stdint.h is present... it seems standardized in 1999? was it already shipped then?

**Comment by msmeissn** [comment]
/usr/include/stdint.h /* Copyright (C) 1997,1998,1999,2000,2001,2006 Free Software Foundation, Inc.
at least in glibc

**Comment by msmeissn** [comment]
also see stdint.h in UnitedLinux 1.0 from 2002.

**Comment by msmeissn** [comment]
merged. we will see if someone reports issues.

**Comment by ndim** [comment]
stdint.h came with C99.

**Pull request merged**
